# Adopted from https://github.com/pybind/pybind11/blob/master/.appveyor.yml

version: 1.3.3 ({build})

skip_branch_with_pr: true

os:
  - Visual Studio 2017

platform:
  - x64

matrix:
  fast_finish: true  # Stop remaining jobs after a job failure

configuration:
  - Release

clone_folder: c:\jet

install:
  - git submodule update --init
  - ps: |
      if ($env:PLATFORM -eq "x64") { $env:CMAKE_ARCH = "x64" }
      if ($env:APPVEYOR_JOB_NAME -like "*Visual Studio 2017*") { $env:CMAKE_GENERATOR = "Visual Studio 15 2017" }
      else { $env:CMAKE_GENERATOR = "Visual Studio 14 2015" }
      $env:PYTHON = "27"
      if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
      $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
      $env:JET_TASKING_SYSTEM = "CPP11Threads"

before_build:
  - md c:\jet\build
  - cd c:\jet\build
  - cmake .. -G "%CMAKE_GENERATOR%" -A "%CMAKE_ARCH%" -DJET_TASKING_SYSTEM=CPP11Threads

build:
  project: c:\jet\build\jet.sln
  parallel: true
  verbosity: normal

after_build:
  - cd c:\jet
  - 7z a jet_py27_vs2017.7z c:\jet\build\ -xr!.vs
  - 7z a jet_external.7z c:\jet\external\
  
artifacts:
  - path: jet_py27_vs2017.7z
    name: 'jet-py27-win-64'
  - path: jet_external.7z
    name: 'jet-external'
